apiVersion: v1
kind: Secret
metadata:
  name: service-order-api-secret
type: Opaque
stringData:
  DATABASE_URL: "${DATABASE_URL}"
  JWT_SECRET: "${JWT_SECRET}"
  APPROVAL_TOKEN_SECRET: "${APPROVAL_TOKEN_SECRET}"
  SMTP_USERNAME: "${SMTP_USERNAME}"
  SMTP_PASSWORD: "${SMTP_PASSWORD}"
